[package]
name = "rusty_website"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "2.1.0"

[lib]
name = "rusty_website"
path = "src/lib.rs"
